/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppSuppliersRouteImport } from './routes/app/suppliers'
import { Route as AppSalesOrdersRouteImport } from './routes/app/sales-orders'
import { Route as AppRolesRouteImport } from './routes/app/roles'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app/purchase-orders'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppPackagingRouteImport } from './routes/app/packaging'
import { Route as AppOutwardRouteImport } from './routes/app/outward'
import { Route as AppOpnameRouteImport } from './routes/app/opname'
import { Route as AppInwardRouteImport } from './routes/app/inward'
import { Route as AppExpiredRouteImport } from './routes/app/expired'
import { Route as AppCustomerRouteImport } from './routes/app/customer'
import { Route as AppActivityLogRouteImport } from './routes/app/activity-log'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPackagingRoute = AppPackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => AppRoute,
} as any)
const AppOutwardRoute = AppOutwardRouteImport.update({
  id: '/outward',
  path: '/outward',
  getParentRoute: () => AppRoute,
} as any)
const AppOpnameRoute = AppOpnameRouteImport.update({
  id: '/opname',
  path: '/opname',
  getParentRoute: () => AppRoute,
} as any)
const AppInwardRoute = AppInwardRouteImport.update({
  id: '/inward',
  path: '/inward',
  getParentRoute: () => AppRoute,
} as any)
const AppExpiredRoute = AppExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomerRoute = AppCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityLogRoute = AppActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/activity-log': typeof AppActivityLogRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/expired': typeof AppExpiredRoute
  '/app/inward': typeof AppInwardRoute
  '/app/opname': typeof AppOpnameRoute
  '/app/outward': typeof AppOutwardRoute
  '/app/packaging': typeof AppPackagingRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/roles': typeof AppRolesRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/activity-log': typeof AppActivityLogRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/expired': typeof AppExpiredRoute
  '/app/inward': typeof AppInwardRoute
  '/app/opname': typeof AppOpnameRoute
  '/app/outward': typeof AppOutwardRoute
  '/app/packaging': typeof AppPackagingRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/roles': typeof AppRolesRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/activity-log': typeof AppActivityLogRoute
  '/app/customer': typeof AppCustomerRoute
  '/app/expired': typeof AppExpiredRoute
  '/app/inward': typeof AppInwardRoute
  '/app/opname': typeof AppOpnameRoute
  '/app/outward': typeof AppOutwardRoute
  '/app/packaging': typeof AppPackagingRoute
  '/app/products': typeof AppProductsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/roles': typeof AppRolesRoute
  '/app/sales-orders': typeof AppSalesOrdersRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/users': typeof AppUsersRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity-log'
    | '/app/customer'
    | '/app/expired'
    | '/app/inward'
    | '/app/opname'
    | '/app/outward'
    | '/app/packaging'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/roles'
    | '/app/sales-orders'
    | '/app/suppliers'
    | '/app/users'
    | '/auth/login'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/activity-log'
    | '/app/customer'
    | '/app/expired'
    | '/app/inward'
    | '/app/opname'
    | '/app/outward'
    | '/app/packaging'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/roles'
    | '/app/sales-orders'
    | '/app/suppliers'
    | '/app/users'
    | '/auth/login'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/activity-log'
    | '/app/customer'
    | '/app/expired'
    | '/app/inward'
    | '/app/opname'
    | '/app/outward'
    | '/app/packaging'
    | '/app/products'
    | '/app/purchase-orders'
    | '/app/roles'
    | '/app/sales-orders'
    | '/app/suppliers'
    | '/app/users'
    | '/auth/login'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales-orders': {
      id: '/app/sales-orders'
      path: '/sales-orders'
      fullPath: '/app/sales-orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/roles': {
      id: '/app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/packaging': {
      id: '/app/packaging'
      path: '/packaging'
      fullPath: '/app/packaging'
      preLoaderRoute: typeof AppPackagingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outward': {
      id: '/app/outward'
      path: '/outward'
      fullPath: '/app/outward'
      preLoaderRoute: typeof AppOutwardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/opname': {
      id: '/app/opname'
      path: '/opname'
      fullPath: '/app/opname'
      preLoaderRoute: typeof AppOpnameRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inward': {
      id: '/app/inward'
      path: '/inward'
      fullPath: '/app/inward'
      preLoaderRoute: typeof AppInwardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expired': {
      id: '/app/expired'
      path: '/expired'
      fullPath: '/app/expired'
      preLoaderRoute: typeof AppExpiredRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customer': {
      id: '/app/customer'
      path: '/customer'
      fullPath: '/app/customer'
      preLoaderRoute: typeof AppCustomerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity-log': {
      id: '/app/activity-log'
      path: '/activity-log'
      fullPath: '/app/activity-log'
      preLoaderRoute: typeof AppActivityLogRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityLogRoute: typeof AppActivityLogRoute
  AppCustomerRoute: typeof AppCustomerRoute
  AppExpiredRoute: typeof AppExpiredRoute
  AppInwardRoute: typeof AppInwardRoute
  AppOpnameRoute: typeof AppOpnameRoute
  AppOutwardRoute: typeof AppOutwardRoute
  AppPackagingRoute: typeof AppPackagingRoute
  AppProductsRoute: typeof AppProductsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityLogRoute: AppActivityLogRoute,
  AppCustomerRoute: AppCustomerRoute,
  AppExpiredRoute: AppExpiredRoute,
  AppInwardRoute: AppInwardRoute,
  AppOpnameRoute: AppOpnameRoute,
  AppOutwardRoute: AppOutwardRoute,
  AppPackagingRoute: AppPackagingRoute,
  AppProductsRoute: AppProductsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
